// <auto-generated />
using System;
using DSI.Persistencia.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DSI.Persistencia.Migrations
{
    [DbContext(typeof(DsiDbContext))]
    [Migration("20260128003328_MigracaoInicial")]
    partial class MigracaoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("DSI.Dominio.Entidades.Conexao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("ModoConexao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("StringConexaoCriptografada")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoBanco")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Nome");

                    b.ToTable("Conexoes", (string)null);
                });

            modelBuilder.Entity("DSI.Dominio.Entidades.ErroExecucao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChaveLinha")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Coluna")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExecucaoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OcorridoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TabelaJobId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TipoRegra")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ValorOriginal")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExecucaoId");

                    b.HasIndex("OcorridoEm");

                    b.HasIndex("TabelaJobId");

                    b.ToTable("ErrosExecucao", (string)null);
                });

            modelBuilder.Entity("DSI.Dominio.Entidades.EstatisticaTabelaExecucao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("DuracaoMs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.Property<Guid>("ExecucaoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("LinhasAtualizadas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("LinhasComErro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("LinhasInseridas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("LinhasLidas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("LinhasPuladas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<Guid>("TabelaJobId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExecucaoId");

                    b.HasIndex("TabelaJobId");

                    b.ToTable("EstatisticasTabelas", (string)null);
                });

            modelBuilder.Entity("DSI.Dominio.Entidades.Execucao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinalizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IniciadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResumoJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IniciadoEm");

                    b.HasIndex("JobId");

                    b.HasIndex("Status");

                    b.HasIndex("JobId", "IniciadoEm");

                    b.ToTable("Execucoes", (string)null);
                });

            modelBuilder.Entity("DSI.Dominio.Entidades.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConexaoDestinoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConexaoOrigemId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("EstrategiaConflito")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Modo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PoliticaErro")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TamanhoLote")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1000);

                    b.HasKey("Id");

                    b.HasIndex("ConexaoDestinoId");

                    b.HasIndex("ConexaoOrigemId");

                    b.HasIndex("Nome");

                    b.ToTable("Jobs", (string)null);
                });

            modelBuilder.Entity("DSI.Dominio.Entidades.Mapeamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColunaDestino")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ColunaOrigem")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ignorada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<Guid>("TabelaJobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoDestino")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ValorConstante")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TabelaJobId");

                    b.ToTable("Mapeamentos", (string)null);
                });

            modelBuilder.Entity("DSI.Dominio.Entidades.Regra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AcaoQuandoFalhar")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MapeamentoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParametrosJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<int>("TipoRegra")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MapeamentoId");

                    b.HasIndex("MapeamentoId", "Ordem");

                    b.ToTable("Regras", (string)null);
                });

            modelBuilder.Entity("DSI.Dominio.Entidades.TabelaJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColunaIncremental")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrdemExecucao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TabelaDestino")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TabelaOrigem")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UltimoCheckpoint")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("JobId", "OrdemExecucao");

                    b.ToTable("TabelasJobs", (string)null);
                });

            modelBuilder.Entity("DSI.Dominio.Entidades.ErroExecucao", b =>
                {
                    b.HasOne("DSI.Dominio.Entidades.Execucao", null)
                        .WithMany("Erros")
                        .HasForeignKey("ExecucaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DSI.Dominio.Entidades.EstatisticaTabelaExecucao", b =>
                {
                    b.HasOne("DSI.Dominio.Entidades.Execucao", null)
                        .WithMany("EstatisticasTabelas")
                        .HasForeignKey("ExecucaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DSI.Dominio.Entidades.Mapeamento", b =>
                {
                    b.HasOne("DSI.Dominio.Entidades.TabelaJob", null)
                        .WithMany("Mapeamentos")
                        .HasForeignKey("TabelaJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DSI.Dominio.Entidades.Regra", b =>
                {
                    b.HasOne("DSI.Dominio.Entidades.Mapeamento", null)
                        .WithMany("Regras")
                        .HasForeignKey("MapeamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DSI.Dominio.Entidades.TabelaJob", b =>
                {
                    b.HasOne("DSI.Dominio.Entidades.Job", null)
                        .WithMany("Tabelas")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DSI.Dominio.Entidades.Execucao", b =>
                {
                    b.Navigation("Erros");

                    b.Navigation("EstatisticasTabelas");
                });

            modelBuilder.Entity("DSI.Dominio.Entidades.Job", b =>
                {
                    b.Navigation("Tabelas");
                });

            modelBuilder.Entity("DSI.Dominio.Entidades.Mapeamento", b =>
                {
                    b.Navigation("Regras");
                });

            modelBuilder.Entity("DSI.Dominio.Entidades.TabelaJob", b =>
                {
                    b.Navigation("Mapeamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
